version:  '3.3'
services:
  uvi_trt_server:
    build:
      context: .
      dockerfile: ./docker/uvicorn_trt_server/Dockerfile
    shm_size: 2gb
    ulimits:
      stack: 67108864
      memlock: -1
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
  trt_server:
    build:
      context: .
      dockerfile: ./docker/trt_server/Dockerfile
    shm_size: 2gb
    ulimits:
      stack: 67108864
      memlock: -1
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
